AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This CloudFormation template is used during the AWS DMS Workshop and creates the following
    - a new VPC (TODO)
    - an Oracle RDS instance
    - a Postgre RDS instance
  
  CAUTION -- You will be billed for the AWS resources used if you create a stack from this template, and are responsible for any/all charges made while running these services in your AWS account
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: 'workshop'
  EC2InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  OracleDBName:
    Default: ORCL
    Description: Enter Oracle Database name
    Type: String
    MinLength: '4'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      must begin with a letter and contain a minimum of 4 alphanumeric
      characters.
  OracleDBPassword:
    Default: oraadmin123
    NoEcho: 'true'
    Description: 'Enter password for the oracle admin user: dbmaster'
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters with minimum of 8 characters.
  OracleDBStorage:
    Default: '100'
    NoEcho: 'false'
    Description: Enter storage for Oracle DB in GB
    Type: Number
    MaxValue: '6000'
    MinValue: '100'
    ConstraintDescription: must contain only numberic and min 100gb less than 6000 GB.
  OracleInstanceType:
    Description: Oracle DB instance type
    Type: String
    Default: db.t2.medium
    AllowedValues:
      - db.t2.medium
    ConstraintDescription: must be a valid Oracle instance type.
  PostgresDBName:
    Default: postgres
    Description: Enter PostgreSQL Database name
    Type: String
    MinLength: '4'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      must begin with a letter and contain a minimum of 4 alphanumeric
      characters.
  PostgresDBUsername:
    Default: postadmin
    NoEcho: 'false'
    Description: Enter database Admin username for RDS PostgreSQL
    Type: String
    MinLength: '4'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      must begin with a letter and contain a minimum of 4 alphanumeric
      characters.
  PostgresDBPassword:
    Default: postadmin123
    NoEcho: 'true'
    Description: Enter password for RDS PostgreSQL Admin user
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters with minimum of 8 characters.
  PostgresInstanceType:
    Description: RDS PostgreSQL DB instance type
    Type: String
    Default: db.t2.medium
    AllowedValues:
      - db.t2.medium
    ConstraintDescription: must be a valid RDS PostgreSQL instance types.
  PostgresDBStorage:
    Default: '100'
    NoEcho: 'false'
    Description: Enter storage for PostgreSQL DB in GB
    Type: Number
    MaxValue: '6000'
    MinValue: '10'
    ConstraintDescription: must contain only numberic and less than 6000 GB.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Source Oracle Database Configuration
        Parameters:
          - OracleDBName
          - OracleDBPassword
          - OracleDBStorage
          - OracleInstanceType
      - Label:
          default: Target PostgreSQL Database Configuration
        Parameters:
          - PostgresDBName
          - PostgresDBUsername
          - PostgresDBPassword
          - PostgresInstanceType
          - PostgresDBStorage
Mappings:
  OracleEngineVersion:
    us-east-1:
      ver: 12.1.0.2.v6
    us-east-2:
      ver: 12.1.0.2.v6
    us-west-1:
      ver: 12.1.0.2.v6
    us-west-2:
      ver: 12.1.0.2.v6
    ap-northeast-1:
      ver: 12.1.0.2.v6
    ap-northeast-2:
      ver: 12.1.0.2.v6
    ap-southeast-1:
      ver: 12.1.0.2.v6
    ap-southeast-2:
      ver: 12.1.0.2.v6
    eu-west-1:
      ver: 12.1.0.2.v6
    eu-central-1:
      ver: 12.1.0.2.v6
    sa-east-1:
      ver: 12.1.0.2.v6
    us-gov-west-1:
      ver: 12.1.0.2.v6
    ap-south-1:
      ver: 12.1.0.2.v6
    cn-north-1:
      ver: 12.1.0.2.v6
  OracleSnapshotId:
    ap-northeast-1:
      snapid: >-
        arn:aws:rds:ap-northeast-1:408917696499:snapshot:apac-dms-workshop-oracle
  PostgresEngineVersion:
    us-east-1:
      ver: 9.6.1
    us-east-2:
      ver: 9.6.1
    us-west-1:
      ver: 9.6.1
    us-west-2:
      ver: 9.6.1
    ap-northeast-1:
      ver: 9.6.1
    ap-northeast-2:
      ver: 9.6.1
    ap-southeast-1:
      ver: 9.6.1
    ap-southeast-2:
      ver: 9.6.1
    eu-west-1:
      ver: 9.6.1
    eu-central-1:
      ver: 9.6.1
    sa-east-1:
      ver: 9.6.1
    us-gov-west-1:
      ver: 9.6.1
    ap-south-1:
      ver: 9.6.1
    cn-north-1:
      ver: 9.6.1
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: !Ref 'AWS::StackName'
  DBSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/26
      AvailabilityZone: !Select 
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  DBSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.64/26
      AvailabilityZone: !Select 
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref DBSubnet1
      RouteTableId: !Ref RouteTable
  SubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref DBSubnet2
      RouteTableId: !Ref RouteTable
  MyDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet available for the DMS Demo RDS DB Instance
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
  OraVPCSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for Oracle Instance.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '1521'
          ToPort: '1521'
          CidrIp: 10.0.0.0/24
  PostgresVPCSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for RDS PostgreSQL Instances.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 10.0.0.0/24
  OracleDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref OracleDBName
      AllocatedStorage: !Ref OracleDBStorage
      MasterUserPassword: !Ref OracleDBPassword
      DBInstanceClass: !Ref OracleInstanceType
      Engine: oracle-ee
      EngineVersion: !FindInMap 
        - OracleEngineVersion
        - !Ref 'AWS::Region'
        - ver
      LicenseModel: bring-your-own-license
      PubliclyAccessible: 'true'
      AvailabilityZone: !GetAtt 
        - DBSubnet1
        - AvailabilityZone
      MultiAZ: 'false'
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref OraVPCSecurityGroup
      DBSnapshotIdentifier: !FindInMap 
        - OracleSnapshotId
        - !Ref 'AWS::Region'
        - snapid
      StorageType: gp2
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  PostgresDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: PostgreSQL Parameter Group  for DMS Testing
      Family: postgres9.6
      Parameters:
        session_replication_role: replica
  PostgresDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref PostgresDBName
      AllocatedStorage: !Ref PostgresDBStorage
      MasterUsername: !Ref PostgresDBUsername
      MasterUserPassword: !Ref PostgresDBPassword
      DBInstanceClass: !Ref PostgresInstanceType
      Engine: postgres
      EngineVersion: !FindInMap 
        - PostgresEngineVersion
        - !Ref 'AWS::Region'
        - ver
      LicenseModel: postgresql-license
      PubliclyAccessible: 'true'
      AvailabilityZone: !GetAtt 
        - DBSubnet1
        - AvailabilityZone
      MultiAZ: 'false'
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref PostgresVPCSecurityGroup
      StorageType: gp2
      DBParameterGroupName: !Ref PostgresDBParameterGroup
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  Regionname:
    Value: !Ref 'AWS::Region'
  OracleJDBCConnectionString:
    Description: JDBC connection string for Oracle database
    Value: !Join 
      - ''
      - - 'jdbc:oracle:thin:@'
        - !GetAtt 
          - OracleDB
          - Endpoint.Address
        - ':'
        - !GetAtt 
          - OracleDB
          - Endpoint.Port
        - ':'
        - !Ref OracleDBName
  PostgresJDBCConnectionString:
    Description: JDBC connection string for PostgreSQL database
    Value: !Join 
      - ''
      - - 'jdbc:postgresql://'
        - !GetAtt 
          - PostgresDB
          - Endpoint.Address
        - ':'
        - !GetAtt 
          - PostgresDB
          - Endpoint.Port
        - /
        - !Ref PostgresDBName